### ISSUE TITLE
PR builds fail when remote branch names contain special characters

### ISSUE THREAD

**Issue by jhmgoossens** [coin-or/COIN-OR-OptimizationSuite#22]
Linux and Windows CI builds for Pull Requests for all project fail if the remote branch name contains a forward slash / because such characters are valid for branch names but not for the uploaded PR asset names. See the discussion in [PR 214 of CoinUtils](https://github.com/coin-or/CoinUtils/pull/214).  

This could be fixes by replacing such characters in the name of the uploaded PR assets, or by leaving out the remote branch name from the PR asset name altogether. 

Since we rarely create PRs from branches with names like _feature/foo_ this is not a very common issue.

**Comment by tkralphs** [comment]
I was originally thinking of a single PR containing all the issues that we can add to over time. Otherwise, it may get a bit difficult to see at a glance how many issues have accumulated. An alternative would be to create a label for Actions-related issues. This is not a bad idea, actually. What do you prefer?

**Comment by jhmgoossens** [comment]
I personally strongly prefer “one issue, one Issue” since this is far easier to tick off as fully Done (or not).

I wasn’t expecting that many issues, but indeed adding a label would be a good idea.

**Comment by tkralphs** [comment]
The issues can accumulate fast :). Anyway, created the label `gh-actions` now.

**Comment by jhmgoossens** [comment]
This can be closed. For PR builds, the remote branch name (head ref) was removed from the artifact names. 
See https://github.com/coin-or/Clp/commit/29b0bb8203d8e94cc40beecdb17ab35bbac54081, https://github.com/coin-or/Cbc/commit/eee5e3fc61fa5abd663c40af8f5231cde325f89f, https://github.com/coin-or/CoinUtils/commit/125379a38f160574e1827a56022db8d34c4481f9, etc.
See also the discussion in Issue #25.
